import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/NavBar";
import DataProvider from "./Components/DataProvider";
import Footer from "./Components/Footer";
import ToastProvider from "./Components/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "KeenKeeper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full hydrated`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <DataProvider>
          <ToastProvider/>
          <NavBar></NavBar>
          {children}
          <Footer></Footer>
        </DataProvider>
      </body>
    </html>
  );
}
