import { discoverValidationDepths } from "next/dist/server/app-render/instant-validation/instant-validation";
import { Suspense } from "react";
import HomePage from "./Components/HomePage";

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <main className="container mx-auto ">
        <Suspense
          fallback={
            <span className="loading loading-spinner loading-xl"></span>
          }
        >
          <HomePage></HomePage>
        </Suspense>
      </main>
    </div>
  );
}
